// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvrcukyyrdswquhwphde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2cmN1a3l5cmRzd3F1aHdwaGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyNTQxMTEsImV4cCI6MjA4ODgzMDExMX0.r69TmAo1rqWaN03WHcTtIkvr4m4X7ITv9W53hlLMLWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});